project:
  type: website
  output-dir: ../docs

website:
  title: "ANLY560 - Phil Cork"
  sidebar:
    style: "docked"
    contents:

      - file: about-author.qmd
        text: About
      - file: index.qmd
        text: Introduction
      - file: data-sources.qmd
        text: Data Sources
      - file: data-visualization.qmd
        text: Data Visualization
      - file: exploratory-data-analysis.qmd
        text: Exploratory Data Analysis
      - file: models.qmd
        text: ARMA/ARIMA/SARIMA Models
      - file: arimax.qmd
        text: ARIMAX/SARIMAX/VAR Models
      - file: spectral-analysis.qmd
        text: Spectral Analysis and Filtering
      - file: financial-ts-models.qmd
        text: Financial Time Series Models
      - file: deep-learning.qmd
        text: Deep Learning for TS
      - file: conclusions.qmd
        text: Conclusions

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

